#!/usr/bin/env node
/**
 * Compiles tokens/*.json into:
 *   src/styles/tokens.css  — CSS custom properties for every theme
 *   src/tokens/index.ts    — typed values for JS/TS consumers
 *
 * The JSON is the only place a raw value is allowed to live. Everything else in
 * the repo — components, stories, docs — reads a generated CSS variable.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PREFIX = 'sable';
const ALIAS = /\{([^}]+)\}/g;

const read = (file) => JSON.parse(readFileSync(resolve(ROOT, 'tokens', file), 'utf8'));

/** Walk a DTCG-ish tree into a flat Map of "a.b.c" -> { value, type }. */
function flatten(node, path = [], out = new Map(), inheritedType) {
  const type = node.$type ?? inheritedType;
  if (Object.hasOwn(node, '$value')) {
    out.set(path.join('.'), { value: String(node.$value), type });
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    if (child && typeof child === 'object') flatten(child, [...path, key], out, type);
  }
  return out;
}

const cssVar = (path) => `--${PREFIX}-${path.replaceAll('.', '-')}`;

/** Rewrite `{color.brand.600}` as `var(--sable-color-brand-600)`, keeping the alias chain intact in CSS. */
const toCssValue = (value) => value.replace(ALIAS, (_, path) => `var(${cssVar(path)})`);

/** Rewrite `{color.brand.600}` as its literal value, for the JS export. */
function toRawValue(value, lookup, trail = []) {
  return value.replace(ALIAS, (_, path) => {
    if (trail.includes(path)) {
      throw new Error(`Circular token alias: ${[...trail, path].join(' -> ')}`);
    }
    const target = lookup.get(path);
    if (!target) throw new Error(`Unknown token alias {${path}}`);
    return toRawValue(target.value, lookup, [...trail, path]);
  });
}

function assertAliasesResolve(tokens, lookup, source) {
  for (const [path, { value }] of tokens) {
    for (const [, ref] of value.matchAll(ALIAS)) {
      if (!lookup.has(ref)) {
        throw new Error(`${source}: token "${path}" references {${ref}}, which does not exist`);
      }
    }
  }
}

/** A theme is only useful if it is total: every name one theme defines, all of them must. */
function assertThemesAgree(themes) {
  const [reference, ...rest] = Object.entries(themes);
  for (const [name, tokens] of rest) {
    const missing = [...reference[1].keys()].filter((k) => !tokens.has(k));
    const extra = [...tokens.keys()].filter((k) => !reference[1].has(k));
    if (missing.length || extra.length) {
      throw new Error(
        [
          `Theme "${name}" does not match theme "${reference[0]}".`,
          missing.length && `  missing: ${missing.join(', ')}`,
          extra.length && `  unexpected: ${extra.join(', ')}`,
        ]
          .filter(Boolean)
          .join('\n'),
      );
    }
  }
}

/** Emit declarations grouped by their top-level namespace, so the output stays readable. */
function declarations(tokens, indent) {
  const lines = [];
  let group = null;
  for (const [path, { value }] of tokens) {
    const next = path.split('.')[0];
    if (next !== group) {
      if (group !== null) lines.push('');
      lines.push(`${indent}/* ${next} */`);
      group = next;
    }
    lines.push(`${indent}${cssVar(path)}: ${toCssValue(value)};`);
  }
  return lines.join('\n');
}

function nest(tokens, lookup) {
  const tree = {};
  for (const [path, { value }] of tokens) {
    const keys = path.split('.');
    let node = tree;
    for (const key of keys.slice(0, -1)) {
      if (typeof node[key] !== 'object' || node[key] === null) node[key] = {};
      node = node[key];
    }
    const last = keys.at(-1);
    if (typeof node[last] === 'object' && node[last] !== null) node[last].DEFAULT = toRawValue(value, lookup);
    else node[last] = toRawValue(value, lookup);
  }
  return tree;
}

const flatTheme = (tokens, lookup) =>
  Object.fromEntries([...tokens].map(([path, { value }]) => [cssVar(path), toRawValue(value, lookup)]));

// ---------------------------------------------------------------------------

const primitives = flatten(read('primitives.json'));
const themeFiles = { light: 'semantic.light.json', dark: 'semantic.dark.json' };
const themes = Object.fromEntries(
  Object.entries(themeFiles).map(([name, file]) => [name, flatten(read(file))]),
);

assertThemesAgree(themes);
assertAliasesResolve(primitives, primitives, 'primitives.json');
for (const [name, tokens] of Object.entries(themes)) {
  const lookup = new Map([...primitives, ...tokens]);
  assertAliasesResolve(tokens, lookup, themeFiles[name]);
}

const banner = `/**
 * Generated by scripts/build-tokens.mjs from tokens/*.json — do not edit by hand.
 * Run \`npm run tokens\` after changing a token.
 */`;

const css = `${banner}

:root {
  color-scheme: light;

${declarations(primitives, '  ')}

  /* --- semantic: light ------------------------------------------------- */

${declarations(themes.light, '  ')}
}

/* Follows the OS unless the page has opted into a theme explicitly. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;

${declarations(themes.dark, '    ')}
  }
}

/* Explicit opt-in, and the escape hatch for theming a subtree. */
[data-theme='dark'] {
  color-scheme: dark;

${declarations(themes.dark, '  ')}
}

[data-theme='light'] {
  color-scheme: light;

${declarations(themes.light, '  ')}
}
`;

const ts = `${banner}

/** Raw primitive values, keyed the same way as tokens/primitives.json. */
export const primitiveTokens = ${JSON.stringify(nest(primitives, primitives), null, 2)} as const;

/** Every semantic CSS variable and the literal value it resolves to, per theme. */
export const themes = ${JSON.stringify(
  Object.fromEntries(
    Object.entries(themes).map(([name, tokens]) => [
      name,
      flatTheme(tokens, new Map([...primitives, ...tokens])),
    ]),
  ),
  null,
  2,
)} as const;

export type ThemeName = keyof typeof themes;

/** Name of any semantic custom property, e.g. \`--${PREFIX}-color-accent-solid\`. */
export type SemanticVariable = keyof (typeof themes)['light'];

/** \`token('color-accent-solid')\` -> \`var(--${PREFIX}-color-accent-solid)\`. */
export function token(name: string): string {
  return \`var(--${PREFIX}-\${name})\`;
}
`;

mkdirSync(resolve(ROOT, 'src/styles'), { recursive: true });
mkdirSync(resolve(ROOT, 'src/tokens'), { recursive: true });
writeFileSync(resolve(ROOT, 'src/styles/tokens.css'), css);
writeFileSync(resolve(ROOT, 'src/tokens/index.ts'), ts);

const count = primitives.size + themes.light.size;
console.log(
  `tokens: ${primitives.size} primitive + ${themes.light.size} semantic x ${Object.keys(themes).length} themes`,
);
console.log(`  -> src/styles/tokens.css (${count} custom properties)`);
console.log('  -> src/tokens/index.ts');
